export const TAGS = {
  "1": "TagA",
  "2": "TagB",
  "3": "TagC",
  "4": "TagD",
  "5": "TagE",
  "6": "TagF",
  "7": "TagG",
  "8": "TagH",
  "9": "TagI",
  "10": "TagJ",
  "11": "TagK",
  "12": "TagL",
  "13": "TagM",
  "14": "TagN",
  "15": "TagO",
  "16": "TagP",
  "17": "TagQ",
  "18": "TagR",
  "19": "TagS",
  "20": "TagT",
};
