export const TAGS = {
  "1": "AI",
  "2": "Data Science",
  "3": "Security",
  "4": "Web Development",
  "5": "Game",
  "6": "Biotech",
  "7": "Business",
  "8": "Start-up",
  "9": "Education",
  "10": "Art & Design",
  "11": "Online",
  "12": "Onsite",
  "13": "Hybrid",
  "14": "High-school",
  "15": "University",
  "16": "TagP",
  "17": "TagQ",
  "18": "TagR",
  "19": "TagS",
  "20": "TagT",
};
