export const UNIVERSITYS = [
  "Asia-Pacific International University",
  "Asian Institute of Technology",
  "Assumption University",
  "Bangkok Suvarnabhumi University",
  "Bangkok Thonburi University",
  "Bangkok University",
  "Bansomdejchaopraya Rajabhat University",
  "Burapha University",
  "Buriram Rajabhat University",
  "Chaiyaphum Rajabhat University",
  "Chalermkarnchana University",
  "Chandrakasem Rajabhat University",
  "Chaopraya University",
  "Chiang Mai Rajabhat University",
  "Chiang Mai University",
  "Chiang Rai Rajabhat University",
  "Christian University of Thailand",
  "Chulabhorn Royal Academy",
  "Chulalongkorn University",
  "Dhonburi Rajabhat University",
  "Dhurakij Pundit University",
  "Eastern Asia University",
  "Fatoni University",
  "Hatyai University",
  "Huachiew Chalermprakiat University",
  "Kalasin University",
  "Kamphaeng Phet Rajabhat University",
  "Kanchanaburi Rajabhat University",
  "Kasem Bundit University",
  "Kasetsart University",
  "Khon Kaen University",
  "King Mongkut's Institute of Technology Ladkrabang",
  "King Mongkut's University of Technology North Bangkok",
  "King Mongkut's University of Technology Thonburi",
  "Krirk University",
  "Lampang Rajabhat University",
  "Loei Rajabhat University",
  "Mae Fah Luang University",
  "Maejo University",
  "Mahachulalongkornrajavidyalaya University",
  "Mahamakut Buddhist University",
  "Mahanakorn University of Technology",
  "Mahasarakham University",
  "Mahidol University",
  "Nakhon Pathom Rajabhat University",
  "Nakhon Phanom University",
  "Nakhon Ratchasima Rajabhat University",
  "Nakhon Sawan Rajabhat University",
  "Nakhon Si Thammarat Rajabhat University",
  "Naresuan University",
  "Navamindradhiraj University",
  "North Bangkok University",
  "Payap University",
  "Pathumthani University",
  "Phetchabun Rajabhat University",
  "Phetchaburi Rajabhat University",
  "Phranakhon Rajabhat University",
  "Phranakhon Si Ayutthaya Rajabhat University",
  "Pibulsongkram Rajabhat University",
  "Prince of Songkla University",
  "Princess of Naradhiwas University",
  "Rajabhat Maha Sarakham University",
  "Rajamangala University of Technology Isan",
  "Rajamangala University of Technology Krungthep",
  "Rajamangala University of Technology Lanna",
  "Rajamangala University of Technology Phra Nakhon",
  "Rajamangala University of Technology Rattanakosin",
  "Rajamangala University of Technology Srivijaya",
  "Rajamangala University of Technology Suvarnabhumi",
  "Rajamangala University of Technology Thanyaburi",
  "Rangsit University",
  "Ramkhamhaeng University",
  "Sripatum University",
  "Srinakharinwirot University",
  "Suan Dusit University",
  "Suan Sunandha Rajabhat University",
  "Sukhothai Thammathirat Open University",
  "Suratthani Rajabhat University",
  "Surindra Rajabhat University",
  "Suranaree University of Technology",
  "Thaksin University",
  "Thammasat University",
  "The Eastern University of Management and Technology",
  "The Far Eastern University",
  "The University of Central Thailand",
  "Thepsatri Rajabhat University",
  "Thonburi University",
  "Ubon Ratchathani Rajabhat University",
  "Ubon Ratchathani University",
  "Udon Thani Rajabhat University",
  "University of Phayao",
  "University of the Thai Chamber of Commerce",
  "Uttaradit Rajabhat University",
  "Valaya Alongkorn Rajabhat University",
  "Vongchavalitkul University",
  "Walailak University",
  "Western University",
  "Yala Rajabhat University",
  "Asian University of Science and Technology",
  "Bangkok North University",
  "Chiangrai University",
  "International Buddhist College",
  "North Eastern University",
  "Rajapark Institute",
  "Rattana Bundit University",
  "Saint John’s University",
  "Shinawatra University",
  "Stamford International University",
  "St. Theresa International College",
  "Taksin University (Private)",
  "Trinity University",
  "University of Phra Nakhon Si Ayutthaya",
  "University of Phitsanulok",
  "University of Uthai Thani",
  "Wesleyan International College",
  "Yonok University",
  "Rajamangala Institute of Technology (older campuses, merged now)",
];
