// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import Navbar from "@/components/Navbar";
import { ChatroomProvider } from "@/context/ChatroomContext";
import { ChatProvider } from "@/context/ChatContext";
import GlobalTracker from "@/components/GlobalTracker";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <ChatroomProvider>
            <ChatProvider>
              {/* <GlobalTracker /> */}
              <Navbar />
              {children}
            </ChatProvider>
          </ChatroomProvider>
        </UserProvider>
      </body>
    </html>
  );
}
